"use client";
import { useEffect, useRef, useState } from "react";
import type { DrumPart } from "@/lib/song-library";

import { analyzeTake, deleteTake, loadTake, saveTake, type SongRecording } from "@/lib/song-recording";
export function SongRecorder({ songId, sectionId, bpm, part, recordings, onSave, onDelete }: { songId: string; sectionId?: string; bpm: number; part?: DrumPart; recordings: SongRecording[]; onSave: (item: SongRecording) => void; onDelete: (id: string) => void }) {
  const recorder = useRef<MediaRecorder | null>(null);
  const stream = useRef<MediaStream | null>(null);
  const startAt = useRef(0);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => () => { if (recorder.current?.state === "recording") { recorder.current.onstop = null; recorder.current.stop(); } stream.current?.getTracks().forEach((track) => track.stop()); }, []);
  const start = async () => { try { stream.current = await navigator.mediaDevices.getUserMedia({ audio: true }); const chunks: BlobPart[] = []; recorder.current = new MediaRecorder(stream.current); recorder.current.ondataavailable = (event) => { if (event.data.size) chunks.push(event.data); }; recorder.current.onstop = async () => { stream.current?.getTracks().forEach((track) => track.stop()); stream.current = null; try { const blob = new Blob(chunks, { type: recorder.current?.mimeType || "audio/webm" }); const id = crypto.randomUUID(); await saveTake(id, blob); const analysis = await analyzeTake(blob, bpm, part).catch(() => ({ hitCount: 0, timingConsistency: null })); onSave({ id, songId, sectionId, createdAt: new Date().toISOString(), durationMs: Date.now() - startAt.current, mimeType: blob.type, ...analysis }); setMessage("Take saved on this device. Timing estimate is approximate."); } catch { setMessage("Could not save this recording."); } setBusy(false); }; startAt.current = Date.now(); recorder.current.start(); setBusy(true); setMessage("Recording locally…"); } catch { setMessage("Microphone permission or recording is unavailable."); } };
  const stop = () => recorder.current?.state === "recording" && recorder.current.stop();
  const exportTake = async (id: string) => { const blob = await loadTake(id); if (!blob) { setMessage("Take not found on this device."); return; } const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; const extension = blob.type.includes("mp4") ? "m4a" : blob.type.includes("ogg") ? "ogg" : "webm"; anchor.download = `drum-hero-take-${id}.${extension}`; anchor.click(); URL.revokeObjectURL(url); };
  return <details><summary>Local recordings</summary><p>Record with microphone permission. Audio remains on this device; export only when you choose. Onsets are matched against this section’s grid after searching for the best start offset. The microphone cannot identify drum voices, and room sound can affect detection, so treat the low/medium confidence score as a rough guide.</p><button type="button" onClick={busy ? stop : start}>{busy ? "Stop recording" : "Record take"}</button><p role="status">{message}</p>{recordings.map((take) => <div key={take.id}><strong>{new Date(take.createdAt).toLocaleString()}</strong> · {Math.round(take.durationMs / 1000)}s · <details className="recording-analysis"><summary>{take.hitCount} detected onsets</summary><ol>{(take.onsetTimes ?? []).map((time, index) => <li key={`${index}-${time}`}>{time.toFixed(2)}s</li>)}</ol></details> · {take.timingConsistency === null ? "Timing unavailable" : `${take.timingConsistency}% expected-hit match · ${take.matchedHits ?? 0} matched, ${take.missedTargets ?? 0} missed, ${take.extraHits ?? 0} extra · ${take.meanOffsetMs ?? "—"} ms mean offset · ${take.confidence ?? "low"} confidence`} <button type="button" onClick={() => void exportTake(take.id)}>Export audio</button><button type="button" onClick={() => void deleteTake(take.id).then(() => onDelete(take.id))}>Delete</button></div>)}</details>;
}
