import type { Groove, Lesson, PracticePattern, Rudiment } from "./types";

const groove = (input: Omit<Groove, "hits"> & { hats?: number[]; kicks?: number[]; snares?: number[]; toms?: number[]; crashes?: number[]; accents?: number[] }): Groove => {
  const { hats = [], kicks = [], snares = [], toms = [], crashes = [], accents = [], ...metadata } = input;
  const add = (steps: number[], instrument: Groove["hits"][number]["instrument"]) => steps.map((step) => ({ step, instrument, accent: accents.includes(step) }));
  return { ...metadata, hits: [...add(hats, "hihat"), ...add(kicks, "kick"), ...add(snares, "snare"), ...add(toms, "tom"), ...add(crashes, "crash")] };
};
const EIGHTHS = [0,1,2,3,4,5,6,7];
const QUARTERS = [0,2,4,6];
const SIXTEENTH_HATS = [0,2,4,6,8,10,12,14];

/** Original teaching patterns in familiar styles; these are generic exercises, not song transcriptions. */
export const grooves: Groove[] = [
  groove({ id:"quarter-pulse", name:"Quarter Note Pulse", level:"Beginner", style:"Foundation", meter:"4/4", feel:"straight", focus:"Keep an even pulse while placing kick and snare", description:"Start with one hi-hat note per beat, kick on 1 and 3, and snare on 2 and 4.", subdivision:4, beats:4, defaultBpm:65, tempoRange:[40,100], hats:[0,1,2,3], kicks:[0,2], snares:[1,3] }),
  groove({ id:"first-beat", name:"First Backbeat", level:"Beginner", style:"Rock", meter:"4/4", feel:"straight", focus:"Steady eighth notes and a strong backbeat", description:"Your first complete beat: hats on eighths, kick on 1 and 3, snare on 2 and 4.", subdivision:8, beats:4, defaultBpm:72, tempoRange:[50,110], hats:EIGHTHS, kicks:[0,4], snares:[2,6] }),
  groove({ id:"straight-pop", name:"Straight Pop Beat", level:"Beginner", style:"Pop", meter:"4/4", feel:"straight", focus:"Keep the eighth-note hat even and the backbeat clear", description:"A steady pop foundation with a consistent kick, snare, and closed hi-hat pattern.", subdivision:8, beats:4, defaultBpm:82, tempoRange:[55,125], hats:EIGHTHS, kicks:[0,4], snares:[2,6] }),
  groove({ id:"two-beat-rock", name:"Two Beat Rock", level:"Beginner", style:"Rock", meter:"4/4", feel:"straight", focus:"Hear a strong snare on beats 2 and 4", description:"A stripped-down rock groove that leaves room to focus on the backbeat.", subdivision:8, beats:4, defaultBpm:78, tempoRange:[50,125], hats:EIGHTHS, kicks:[0], snares:[2,6] }),
  groove({ id:"four-on-floor", name:"Four on the Floor", level:"Beginner", style:"Dance / Disco", meter:"4/4", feel:"straight", focus:"Keep four steady kick notes under the backbeat", description:"Kick every beat, snare on 2 and 4, and even eighth-note hi-hat.", subdivision:8, beats:4, defaultBpm:112, tempoRange:[75,135], hats:EIGHTHS, kicks:QUARTERS, snares:[2,6] }),
  groove({ id:"half-time-rock", name:"Half Time Rock", level:"Beginner", style:"Rock", meter:"4/4", feel:"straight", focus:"Leave space and place the snare on beat 3", description:"The pulse stays steady while the snare lands once per bar on beat 3.", subdivision:8, beats:4, defaultBpm:76, tempoRange:[50,115], hats:EIGHTHS, kicks:[0,5], snares:[4] }),
  groove({ id:"punk-drive", name:"Punk Drive", level:"Beginner", style:"Punk", meter:"4/4", feel:"straight", focus:"Keep the eighth notes even at a brisk tempo", description:"A fast, straight eighth-note groove with a firm kick and backbeat.", subdivision:8, beats:4, defaultBpm:138, tempoRange:[90,180], hats:EIGHTHS, kicks:[0,4], snares:[2,6], crashes:[0], accents:[0,2,4,6] }),
  groove({ id:"disco-open-hat", name:"Disco Offbeat Hat", level:"Intermediate", style:"Dance / Disco", meter:"4/4", feel:"straight", focus:"Lift the offbeat hi-hat without rushing the kick", description:"Four-on-the-floor kick with a lifted offbeat hat accent and steady backbeat.", subdivision:8, beats:4, defaultBpm:116, tempoRange:[80,140], hats:EIGHTHS, kicks:QUARTERS, snares:[2,6], accents:[1,3,5,7] }),
  groove({ id:"motown-pocket", name:"Motown Pocket", level:"Intermediate", style:"Soul", meter:"4/4", feel:"straight", focus:"Make the kick and backbeat feel relaxed and consistent", description:"A warm eighth-note pocket with a small kick pickup into beat 3.", subdivision:8, beats:4, defaultBpm:96, tempoRange:[65,125], hats:EIGHTHS, kicks:[0,3,4], snares:[2,6] }),
  groove({ id:"reggae-one-drop", name:"Reggae One Drop", level:"Intermediate", style:"Reggae", meter:"4/4", feel:"straight", focus:"Leave beat 1 open and land the band hit on beat 3", description:"Kick and snare meet on beat 3 while the hi-hat carries the pulse.", subdivision:8, beats:4, defaultBpm:78, tempoRange:[55,110], hats:EIGHTHS, kicks:[4], snares:[4] }),
  groove({ id:"reggae-steppers", name:"Reggae Steppers", level:"Intermediate", style:"Reggae", meter:"4/4", feel:"straight", focus:"Keep an even quarter-note kick beneath the hat", description:"A steady kick on every beat with a light backbeat on 2 and 4.", subdivision:8, beats:4, defaultBpm:84, tempoRange:[60,120], hats:EIGHTHS, kicks:QUARTERS, snares:[2,6] }),
  groove({ id:"ska-upbeat", name:"Ska Upbeat", level:"Intermediate", style:"Ska", meter:"4/4", feel:"straight", focus:"Place the snare on the offbeat eighth notes", description:"A brisk upbeat pattern with snare on the '&' counts and kick on the quarter pulse.", subdivision:8, beats:4, defaultBpm:126, tempoRange:[85,165], hats:EIGHTHS, kicks:[0,4], snares:[1,3,5,7] }),
  groove({ id:"country-train", name:"Country Train Beat", level:"Intermediate", style:"Country", meter:"4/4", feel:"straight", focus:"Alternate kick and snare evenly under the hats", description:"A driving train-like pattern with an alternating low and backbeat voice.", subdivision:8, beats:4, defaultBpm:104, tempoRange:[70,140], hats:EIGHTHS, kicks:[0,4], snares:[2,6], accents:[0,2,4,6] }),
  groove({ id:"shuffle-blues", name:"Blues Shuffle", level:"Intermediate", style:"Blues", meter:"4/4", feel:"triplet", focus:"Keep the long-short triplet feel relaxed", description:"A swung triplet-grid shuffle with kick on 1 and 3 and snare on 2 and 4.", subdivision:12, beats:4, defaultBpm:82, tempoRange:[55,120], hats:[0,2,3,5,6,8,9,11], kicks:[0,6], snares:[3,9] }),
  groove({ id:"jazz-swing", name:"Jazz Swing Ride Pattern", level:"Intermediate", style:"Jazz", meter:"4/4", feel:"triplet", focus:"Ride the triplet pulse and keep the feathered kick quiet", description:"A basic swung ride pattern with a light hi-hat on beats 2 and 4. Use the hi-hat voice as your ride cymbal guide.", subdivision:12, beats:4, defaultBpm:112, tempoRange:[70,160], hats:[0,2,3,5,6,8,9,11], kicks:[0,3,6,9], snares:[3,9], accents:[0,3,6,9] }),
  groove({ id:"bossa-nova", name:"Bossa Nova", level:"Advanced", style:"Latin", meter:"4/4", feel:"straight", focus:"Keep the cross-stick backbeat while the kick syncopates", description:"An original bossa-inspired coordination study with a syncopated kick and steady eighth-note guide.", subdivision:8, beats:4, defaultBpm:112, tempoRange:[75,155], hats:EIGHTHS, kicks:[0,3,5], snares:[2,6], accents:[2,6] }),
  groove({ id:"samba-drive", name:"Samba Drive", level:"Advanced", style:"Latin", meter:"4/4", feel:"straight", focus:"Coordinate the repeating kick figure against the backbeat", description:"A brisk, original samba-inspired kit exercise with repeated bass drum notes.", subdivision:16, beats:4, defaultBpm:104, tempoRange:[70,150], hats:SIXTEENTH_HATS, kicks:[0,3,6,9,12], snares:[4,12] }),
  groove({ id:"syncopated-funk", name:"Syncopated Funk Pocket", level:"Advanced", style:"Funk", meter:"4/4", feel:"straight", focus:"Place offbeat kicks without disturbing the backbeat", description:"Anchor the snare while the kick moves between the pulse; keep sixteenth-note subdivisions clear.", subdivision:16, beats:4, defaultBpm:88, tempoRange:[60,125], hats:SIXTEENTH_HATS, kicks:[0,3,10], snares:[4,12] }),
  groove({ id:"broken-beat", name:"Broken Beat", level:"Advanced", style:"Funk / R&B", meter:"4/4", feel:"straight", focus:"Count the sixteenths while the accents shift around the bar", description:"A syncopated study in displaced kick and snare accents over a steady subdivision.", subdivision:16, beats:4, defaultBpm:96, tempoRange:[60,140], hats:SIXTEENTH_HATS, kicks:[0,7,10], snares:[4,11,14] }),
  groove({ id:"five-four-drive", name:"Five-Four Drive", level:"Advanced", style:"Odd meter", meter:"5/4 (3 + 2)", feel:"straight", focus:"Feel five as 3 + 2", description:"A musical five-beat groove with a clear grouping.", subdivision:8, beats:5, defaultBpm:105, tempoRange:[70,150], hats:Array.from({length:10},(_,step)=>step), kicks:[0,6], snares:[4,8] }),
  groove({ id:"seven-eight-group", name:"Seven-Eight Grouping", level:"Advanced", style:"Odd meter", meter:"7/8 (2 + 2 + 3)", feel:"straight", focus:"Group the seven eighth notes as 2 + 2 + 3", description:"A short odd-meter phrase with a clear kick grouping and a snare anchor near the end.", subdivision:8, beats:3.5, defaultBpm:92, tempoRange:[55,135], hats:Array.from({length:7},(_,step)=>step), kicks:[0,2,4], snares:[4] }),
  groove({ id:"five-four-half-time", name:"Five-Four Half Time", level:"Advanced", style:"Odd meter", meter:"5/4", feel:"straight", focus:"Hold the five-beat phrase while leaving space around the snare", description:"An open five-beat groove with a half-time backbeat and a steady eighth-note guide.", subdivision:8, beats:5, defaultBpm:90, tempoRange:[60,135], hats:Array.from({length:10},(_,step)=>step), kicks:[0,6], snares:[4] }),
  groove({ id:"sparse-rock-backbeat", name:"Sparse Rock Backbeat", level:"Beginner", style:"Rock", meter:"4/4", feel:"straight", focus:"Keep the backbeat steady while leaving the kick space", description:"A relaxed eighth-note hat line with only one kick and a clear two-and-four snare.", subdivision:8, beats:4, defaultBpm:68, tempoRange:[45,105], hats:EIGHTHS, kicks:[0], snares:[2,6] }),
  groove({ id:"quarter-kick-backbeat", name:"Quarter Kick Backbeat", level:"Beginner", style:"Foundation", meter:"4/4", feel:"straight", focus:"Keep the kick even under a steady backbeat", description:"Quarter-note kicks support the familiar snare on beats two and four.", subdivision:8, beats:4, defaultBpm:74, tempoRange:[45,115], hats:[0,2,4,6], kicks:QUARTERS, snares:[2,6] }),
  groove({ id:"slow-rock-drive", name:"Slow Rock Drive", level:"Beginner", style:"Rock", meter:"4/4", feel:"straight", focus:"Stay relaxed through a slow eighth-note pattern", description:"A slow, open rock beat that helps build even hands and dependable snare placement.", subdivision:8, beats:4, defaultBpm:60, tempoRange:[40,95], hats:EIGHTHS, kicks:[0,4], snares:[2,6] }),
  groove({ id:"kick-pickup-intro", name:"Kick Pickup Intro", level:"Beginner", style:"Foundation", meter:"4/4", feel:"straight", focus:"Place a simple pickup without rushing the next bar", description:"Add one extra kick on the final offbeat while the hi-hat and backbeat stay steady.", subdivision:8, beats:4, defaultBpm:70, tempoRange:[45,110], hats:EIGHTHS, kicks:[0,4,7], snares:[2,6] }),
  groove({ id:"tom-pulse-intro", name:"Tom Pulse", level:"Beginner", style:"Foundation", meter:"4/4", feel:"straight", focus:"Move between tom and snare while keeping the pulse", description:"A simple alternating tom and snare exercise with an eighth-note guide.", subdivision:8, beats:4, defaultBpm:72, tempoRange:[45,110], hats:EIGHTHS, kicks:[0,4], snares:[2,6], toms:[3,7] }),
  groove({ id:"three-four-waltz", name:"Three-Quarter Waltz", level:"Beginner", style:"Waltz", meter:"3/4", feel:"straight", focus:"Feel the first beat of each three-beat bar", description:"A simple waltz pulse with kick on one, snare on two, and a light final beat.", subdivision:8, beats:3, defaultBpm:78, tempoRange:[50,120], hats:[0,1,2,3,4,5], kicks:[0], snares:[2], accents:[0] }),
  groove({ id:"six-eight-first-step", name:"First Six-Eight Pulse", level:"Beginner", style:"Compound meter", meter:"6/8", feel:"straight", focus:"Count six even eighth notes in two groups of three", description:"A basic compound-meter exercise with kick on the first pulse and snare on the fourth.", subdivision:8, beats:3, defaultBpm:76, tempoRange:[50,115], hats:[0,1,2,3,4,5], kicks:[0], snares:[3], accents:[0,3] }),
  groove({ id:"backbeat-quarters", name:"Quarter-Note Backbeat", level:"Beginner", style:"Foundation", meter:"4/4", feel:"straight", focus:"Keep quarter notes even and put the snare on two and four", description:"A sparse pattern with one note per beat across the hi-hat, kick, and snare.", subdivision:4, beats:4, defaultBpm:66, tempoRange:[40,105], hats:[0,1,2,3], kicks:[0,2], snares:[1,3], accents:[0,1,2,3] }),
  groove({ id:"two-bar-hat-dynamics", name:"Hat Accent Alternation", level:"Beginner", style:"Coordination", meter:"4/4", feel:"straight", focus:"Alternate strong downbeats with quieter offbeats", description:"Play eight steady hi-hat notes and make the main beats stand out from the offbeats.", subdivision:8, beats:4, defaultBpm:72, tempoRange:[45,115], hats:EIGHTHS, kicks:[0,4], snares:[2,6], accents:[0,2,4,6] }),
  groove({ id:"beginner-crash-land", name:"Crash and Land", level:"Beginner", style:"Rock", meter:"4/4", feel:"straight", focus:"Coordinate a crash with the first kick", description:"Start the bar with a crash and kick together, then settle into a simple backbeat.", subdivision:8, beats:4, defaultBpm:76, tempoRange:[50,120], hats:EIGHTHS, kicks:[0,4], snares:[2,6], crashes:[0], accents:[0] }),
  groove({ id:"easy-four-kicks", name:"Four Even Kicks", level:"Beginner", style:"Dance", meter:"4/4", feel:"straight", focus:"Keep the bass drum even on every beat", description:"Four quarter-note kicks create a stable base under the two-and-four backbeat.", subdivision:8, beats:4, defaultBpm:90, tempoRange:[55,125], hats:EIGHTHS, kicks:[0,2,4,6], snares:[2,6] }),
  groove({ id:"rock-syncopation-step", name:"Rock Kick Pickup", level:"Intermediate", style:"Rock", meter:"4/4", feel:"straight", focus:"Place the kick pickup on the final eighth note", description:"A familiar backbeat with a kick pickup that pulls the phrase into the next bar.", subdivision:8, beats:4, defaultBpm:92, tempoRange:[60,135], hats:EIGHTHS, kicks:[0,4,7], snares:[2,6] }),
  groove({ id:"rock-syncopation-two", name:"Rock Offbeat Kick", level:"Intermediate", style:"Rock", meter:"4/4", feel:"straight", focus:"Keep an offbeat kick from pulling the snare forward", description:"Shift one bass drum note to the '&' after beat two while the snare anchors two and four.", subdivision:8, beats:4, defaultBpm:96, tempoRange:[60,140], hats:EIGHTHS, kicks:[0,3,4], snares:[2,6] }),
  groove({ id:"indie-open-space", name:"Indie Open Space", level:"Intermediate", style:"Indie Rock", meter:"4/4", feel:"straight", focus:"Hold time through a bar with fewer kick notes", description:"The hats and backbeat keep moving while the kick leaves room between its two notes.", subdivision:8, beats:4, defaultBpm:88, tempoRange:[55,130], hats:EIGHTHS, kicks:[0,7], snares:[2,6] }),
  groove({ id:"rnb-sixteenth-pocket", name:"Sixteenth R&B Pocket", level:"Intermediate", style:"R&B", meter:"4/4", feel:"straight", focus:"Count sixteenth notes while keeping the snare settled", description:"A lightly syncopated kick and snare pattern over a full sixteenth-note hat guide.", subdivision:16, beats:4, defaultBpm:82, tempoRange:[55,120], hats:Array.from({length:16},(_,step)=>step), kicks:[0,7,10], snares:[4,12], accents:[0,4,8,12] }),
  groove({ id:"ghost-note-pocket", name:"Ghost Note Pocket", level:"Intermediate", style:"Funk", meter:"4/4", feel:"straight", focus:"Separate quiet snare taps from backbeat accents", description:"Keep the main backbeat strong and place softer snare notes around it.", subdivision:16, beats:4, defaultBpm:78, tempoRange:[50,120], hats:SIXTEENTH_HATS, kicks:[0,7,10], snares:[4,7,11,12], accents:[4,12] }),
  groove({ id:"disco-sixteenth-drive", name:"Sixteenth Disco Drive", level:"Intermediate", style:"Dance / Disco", meter:"4/4", feel:"straight", focus:"Keep the kick on each beat while the hand subdivides", description:"Four-on-the-floor kick under a continuous sixteenth-note hat pattern and steady snare.", subdivision:16, beats:4, defaultBpm:112, tempoRange:[75,140], hats:Array.from({length:16},(_,step)=>step), kicks:[0,4,8,12], snares:[4,12], accents:[0,4,8,12] }),
  groove({ id:"classic-shuffle-pocket", name:"Classic Shuffle Pocket", level:"Intermediate", style:"Blues", meter:"4/4", feel:"triplet", focus:"Keep the skipped triplet note light", description:"A swung triplet hat line with kick on one and three and snare on two and four.", subdivision:12, beats:4, defaultBpm:86, tempoRange:[55,125], hats:[0,2,3,5,6,8,9,11], kicks:[0,6], snares:[3,9] }),
  groove({ id:"shuffle-kick-walk", name:"Walking Shuffle Kick", level:"Intermediate", style:"Blues", meter:"4/4", feel:"triplet", focus:"Maintain the shuffle while the kick walks through the bar", description:"A triplet shuffle with an extra kick note leading into the second half of the measure.", subdivision:12, beats:4, defaultBpm:90, tempoRange:[60,130], hats:[0,2,3,5,6,8,9,11], kicks:[0,5,6,11], snares:[3,9] }),
  groove({ id:"jazz-ride-basic-comp", name:"Ride and Comp", level:"Intermediate", style:"Jazz", meter:"4/4", feel:"triplet", focus:"Keep the ride flowing while placing snare comp notes", description:"A ride-like triplet guide with sparse snare comping and a light hi-hat on two and four.", subdivision:12, beats:4, defaultBpm:118, tempoRange:[75,165], hats:[0,3,6,9], kicks:[0,3,6,9], snares:[3,8,9], accents:[0,3,6,9] }),
  groove({ id:"ska-two-step", name:"Ska Two-Step", level:"Intermediate", style:"Ska", meter:"4/4", feel:"straight", focus:"Keep the upbeat snares light and even", description:"A brisk two-and-four kick with snare notes on the eighth-note upbeats.", subdivision:8, beats:4, defaultBpm:132, tempoRange:[90,170], hats:EIGHTHS, kicks:[0,4], snares:[1,3,5,7] }),
  groove({ id:"reggae-rockers", name:"Reggae Rockers", level:"Intermediate", style:"Reggae", meter:"4/4", feel:"straight", focus:"Keep the kick on each beat with a relaxed backbeat", description:"A steady roots-style kit exercise with four kicks and a light snare on two and four.", subdivision:8, beats:4, defaultBpm:88, tempoRange:[55,125], hats:EIGHTHS, kicks:QUARTERS, snares:[2,6], accents:[2,6] }),
  groove({ id:"afrobeat-interlock", name:"Afrobeat Interlock", level:"Intermediate", style:"Afrobeat", meter:"4/4", feel:"straight", focus:"Coordinate a repeating kick figure under even hats", description:"A repeating syncopated kick line and sparse snare pattern make a coordination study.", subdivision:16, beats:4, defaultBpm:96, tempoRange:[60,135], hats:SIXTEENTH_HATS, kicks:[0,3,6,8,11,14], snares:[4,12] }),
  groove({ id:"soul-hat-lift", name:"Soul Hat Lift", level:"Intermediate", style:"Soul", meter:"4/4", feel:"straight", focus:"Lift selected hat notes without changing the backbeat", description:"A steady soul groove with selected offbeat hi-hat accents and a moving kick pickup.", subdivision:8, beats:4, defaultBpm:98, tempoRange:[65,135], hats:EIGHTHS, kicks:[0,3,4,7], snares:[2,6], accents:[1,5] }),
  groove({ id:"three-four-rock", name:"Three-Quarter Rock", level:"Intermediate", style:"Rock", meter:"3/4", feel:"straight", focus:"Place the backbeat on beat three of a waltz bar", description:"A rock pattern in three with a kick on one and a snare on three.", subdivision:8, beats:3, defaultBpm:102, tempoRange:[65,145], hats:[0,1,2,3,4,5], kicks:[0,4], snares:[4], accents:[0,4] }),
  groove({ id:"six-eight-blues", name:"Six-Eight Blues", level:"Intermediate", style:"Blues", meter:"6/8", feel:"triplet", focus:"Group the six pulses into two groups of three", description:"A compound-time shuffle with a bass drum on the first pulse and snare on the fourth.", subdivision:8, beats:3, defaultBpm:84, tempoRange:[55,125], hats:[0,1,2,3,4,5], kicks:[0,2], snares:[3], accents:[0,3] }),
  groove({ id:"four-on-floor-open", name:"Four-on-the-Floor Hat Lift", level:"Intermediate", style:"Dance / Disco", meter:"4/4", feel:"straight", focus:"Keep every kick solid as the hat accents move", description:"A four-kick dance pattern with a lifted offbeat hat accent and a stable snare.", subdivision:8, beats:4, defaultBpm:120, tempoRange:[80,150], hats:EIGHTHS, kicks:QUARTERS, snares:[2,6], accents:[1,3,5,7] }),
  groove({ id:"straight-sixteenth-rock", name:"Straight Sixteenth Rock", level:"Intermediate", style:"Rock", meter:"4/4", feel:"straight", focus:"Keep the sixteenth-note hand motion even", description:"A straight rock backbeat beneath a full sixteenth-note hi-hat guide.", subdivision:16, beats:4, defaultBpm:90, tempoRange:[60,135], hats:Array.from({length:16},(_,step)=>step), kicks:[0,8], snares:[4,12], accents:[0,4,8,12] }),
  groove({ id:"latin-cascara-study", name:"Cascara-Inspired Study", level:"Intermediate", style:"Latin", meter:"4/4", feel:"straight", focus:"Keep the repeating bell-like hand pattern even", description:"An original coordination study with a repeating accented hand pattern and syncopated kick.", subdivision:16, beats:4, defaultBpm:104, tempoRange:[70,145], hats:[0,3,6,8,11,14], kicks:[0,6,10], snares:[4,12], accents:[0,6,8,14] }),
  groove({ id:"funk-linear-basics", name:"Linear Funk Basics", level:"Advanced", style:"Funk", meter:"4/4", feel:"straight", focus:"Keep kick, snare, and hat strokes from colliding", description:"A linear sixteenth-note phrase that moves between voices while maintaining the pulse.", subdivision:16, beats:4, defaultBpm:82, tempoRange:[55,125], hats:[0,2,5,8,10,13], kicks:[0,3,7,10,14], snares:[4,11,15], accents:[0,4,8,12] }),
  groove({ id:"double-kick-metal", name:"Double-Kick Metal Grid", level:"Advanced", style:"Metal", meter:"4/4", feel:"straight", focus:"Keep fast bass drum notes even beneath the backbeat", description:"A demanding sixteenth-note kick ostinato with a steady snare and eighth-note hand guide.", subdivision:16, beats:4, defaultBpm:108, tempoRange:[65,165], hats:SIXTEENTH_HATS, kicks:Array.from({length:16},(_,step)=>step), snares:[4,12], accents:[0,4,8,12] }),
  groove({ id:"drum-and-bass-half-time", name:"Drum and Bass Half-Time", level:"Advanced", style:"Drum and Bass", meter:"4/4", feel:"straight", focus:"Feel the half-time snare against a quick subdivision", description:"A brisk sixteenth-note guide with a spacious snare on beat three and syncopated kick.", subdivision:16, beats:4, defaultBpm:88, tempoRange:[55,130], hats:Array.from({length:16},(_,step)=>step), kicks:[0,7,10], snares:[8], accents:[0,8] }),
  groove({ id:"gospel-sixteenth-pocket", name:"Gospel Sixteenth Pocket", level:"Advanced", style:"Gospel", meter:"4/4", feel:"straight", focus:"Fit displaced snare accents around the anchor beats", description:"A busy sixteenth-note coordination pattern with syncopated kick and snare accents.", subdivision:16, beats:4, defaultBpm:94, tempoRange:[60,140], hats:SIXTEENTH_HATS, kicks:[0,3,6,10,14], snares:[4,7,11,12,15], accents:[4,12] }),
  groove({ id:"second-line-study", name:"Second-Line Study", level:"Advanced", style:"New Orleans", meter:"4/4", feel:"straight", focus:"Maintain a buoyant pulse through syncopated accents", description:"An original parade-style coordination exercise with displaced snare and kick accents.", subdivision:8, beats:4, defaultBpm:110, tempoRange:[75,150], hats:EIGHTHS, kicks:[0,3,4,7], snares:[2,5,6], accents:[0,4] }),
  groove({ id:"latin-clave-coordination", name:"Clave Coordination Study", level:"Advanced", style:"Latin", meter:"4/4", feel:"straight", focus:"Keep a two-bar accent phrase steady across the bar line", description:"A two-bar-inspired, original kit coordination pattern with shifting accents and open space.", subdivision:16, beats:4, defaultBpm:98, tempoRange:[60,140], hats:[0,2,4,6,8,10,12,14], kicks:[0,5,8,11], snares:[4,12], accents:[0,5,8,11] }),
  groove({ id:"six-eight-rock-drive", name:"Six-Eight Rock Drive", level:"Advanced", style:"Rock", meter:"6/8", feel:"straight", focus:"Drive two groups of three without flattening the meter", description:"A strong compound rock pulse with bass drum on one and four and snare on four.", subdivision:8, beats:3, defaultBpm:108, tempoRange:[70,150], hats:[0,1,2,3,4,5], kicks:[0,3], snares:[3], accents:[0,3] }),
  groove({ id:"twelve-eight-shuffle", name:"Twelve-Eight Slow Shuffle", level:"Advanced", style:"Blues", meter:"12/8", feel:"triplet", focus:"Hold four triplet groups with a deep backbeat", description:"A spacious triplet-grid groove with a rolling ride guide and backbeat on beats two and four.", subdivision:12, beats:4, defaultBpm:72, tempoRange:[45,110], hats:[0,1,2,3,4,5,6,7,8,9,10,11], kicks:[0,6], snares:[3,9], accents:[0,3,6,9] }),
  groove({ id:"nine-eight-grouping", name:"Nine-Eight Grouping", level:"Advanced", style:"Odd meter", meter:"9/8 (2 + 2 + 2 + 3)", feel:"straight", focus:"Hear the final group of three before the bar turns", description:"An odd-meter exercise with nine eighth-note steps grouped as two, two, two, and three.", subdivision:8, beats:4.5, defaultBpm:88, tempoRange:[55,135], hats:Array.from({length:9},(_,step)=>step), kicks:[0,4,6], snares:[2,8], accents:[0,4,6] }),
  groove({ id:"seven-eight-long-group", name:"Seven-Eight 3 + 2 + 2", level:"Advanced", style:"Odd meter", meter:"7/8 (3 + 2 + 2)", feel:"straight", focus:"Keep the three-note opening group distinct", description:"A seven-eighth phrase grouped as three, two, and two with clear kick and snare anchors.", subdivision:8, beats:3.5, defaultBpm:96, tempoRange:[60,140], hats:Array.from({length:7},(_,step)=>step), kicks:[0,3,5], snares:[2,6], accents:[0,3,5] }),
  groove({ id:"five-four-two-three", name:"Five-Four 2 + 3", level:"Advanced", style:"Odd meter", meter:"5/4 (2 + 3)", feel:"straight", focus:"Feel the two-beat pickup into the longer group", description:"A five-beat rock phrase grouped as two plus three with a stable eighth-note guide.", subdivision:8, beats:5, defaultBpm:100, tempoRange:[65,145], hats:Array.from({length:10},(_,step)=>step), kicks:[0,4,6], snares:[2,8], accents:[0,4,6] }),
  groove({ id:"five-four-syncopated", name:"Five-Four Syncopation", level:"Advanced", style:"Odd meter", meter:"5/4 (3 + 2)", feel:"straight", focus:"Keep syncopated kicks inside the five-beat phrase", description:"A more displaced kick pattern over a five-beat grouping, with snare notes marking the turns.", subdivision:16, beats:5, defaultBpm:92, tempoRange:[60,135], hats:Array.from({length:20},(_,step)=>step), kicks:[0,5,8,14,17], snares:[4,12,16], accents:[0,8,16] }),
  groove({ id:"three-four-jazz-waltz", name:"Jazz Waltz Ride", level:"Advanced", style:"Jazz", meter:"3/4", feel:"triplet", focus:"Keep the triplet ride flowing across three beats", description:"A triplet-grid ride pattern with light kick support and sparse snare comping.", subdivision:12, beats:3, defaultBpm:126, tempoRange:[80,175], hats:[0,2,3,5,6,8], kicks:[0,3,6], snares:[2,7], accents:[0,3,6] }),
  groove({ id:"twelve-eight-gospel", name:"Twelve-Eight Gospel Pulse", level:"Advanced", style:"Gospel", meter:"12/8", feel:"triplet", focus:"Keep a flowing triplet hand while displacing the kick", description:"A compound triplet exercise with a steady guide, moving kick, and backbeat anchors.", subdivision:12, beats:4, defaultBpm:94, tempoRange:[60,140], hats:[0,1,2,3,4,5,6,7,8,9,10,11], kicks:[0,5,6,11], snares:[3,9], accents:[0,3,6,9] }),
  groove({ id:"broken-sixteenth-hats", name:"Broken Sixteenth Hats", level:"Advanced", style:"Funk / R&B", meter:"4/4", feel:"straight", focus:"Keep a consistent internal sixteenth-note count", description:"A broken hat orchestration with gaps while syncopated kit voices fill the rhythmic space.", subdivision:16, beats:4, defaultBpm:102, tempoRange:[65,145], hats:[0,2,5,7,8,10,13,15], kicks:[0,6,11], snares:[4,12], accents:[0,8] }),
  groove({ id:"four-over-three-accent", name:"Four-Beat Accent Displacement", level:"Advanced", style:"Coordination", meter:"4/4", feel:"straight", focus:"Hold the backbeat while accents shift every three steps", description:"A repeating accent cycle crosses the bar line over a stable four-beat foundation.", subdivision:16, beats:4, defaultBpm:84, tempoRange:[55,125], hats:SIXTEENTH_HATS, kicks:[0,8], snares:[4,12], accents:[0,3,6,9,12,15] }),
  groove({ id:"one-bar-tom-ascent", name:"One-Bar Tom Ascent", level:"Intermediate", style:"Fill study", meter:"4/4", feel:"straight", focus:"Move a steady sixteenth-note fill around the kit", description:"A one-bar fill study that moves from snare to toms and lands on a crash.", subdivision:16, beats:4, defaultBpm:76, tempoRange:[50,115], snares:[0,1,2,3,4,5,6,7], toms:[8,9,10,11,12,13,14], crashes:[15], accents:[0,4,8,12,15] }),
  groove({ id:"one-bar-tom-descent", name:"One-Bar Tom Descent", level:"Intermediate", style:"Fill study", meter:"4/4", feel:"straight", focus:"Play even singles while moving down the toms", description:"A descending fill that travels from high tom back to snare with a clear final accent.", subdivision:16, beats:4, defaultBpm:82, tempoRange:[55,120], toms:[0,1,2,3,4,5,6,7,8,9,10,11], snares:[12,13,14], crashes:[15], accents:[0,4,8,12,15] }),
  groove({ id:"one-bar-linear-fill", name:"One-Bar Linear Fill", level:"Advanced", style:"Fill study", meter:"4/4", feel:"straight", focus:"Play the fill without overlapping drum voices", description:"A challenging linear fill where each sixteenth-note step moves to a different kit voice.", subdivision:16, beats:4, defaultBpm:78, tempoRange:[50,120], kicks:[0,6,10], snares:[2,4,8,12], toms:[1,3,5,7,9,11,13,14], crashes:[15], accents:[0,4,8,12,15] }),
  groove({ id:"rock-groove-into-fill", name:"Rock Groove → Fill", level:"Intermediate", style:"Groove + fill", meter:"2 bars · 4/4", feel:"straight", focus:"Keep the first bar steady and make the second-bar fill resolve", description:"Play a straight rock beat for one bar, then move through a simple snare and tom fill. The phrase loops back to the downbeat.", subdivision:16, beats:8, defaultBpm:82, tempoRange:[55,125], hats:[0,2,4,6,8,10,12,14], kicks:[0,8,16,24], snares:[4,12,20,24,26,28], toms:[21,22,23,25,27,29,30], crashes:[0,31], accents:[0,4,8,12,16,24,31] }),
  groove({ id:"pop-groove-into-fill", name:"Pop Groove → Fill", level:"Intermediate", style:"Groove + fill", meter:"2 bars · 4/4", feel:"straight", focus:"Keep the pop backbeat clear before a compact fill", description:"A steady pop bar followed by a short tom fill and a crash to lead into the next loop.", subdivision:16, beats:8, defaultBpm:94, tempoRange:[60,135], hats:[0,2,4,6,8,10,12,14], kicks:[0,8,16,24,30], snares:[4,12,20,28], toms:[25,26,27,29], crashes:[0,31], accents:[0,4,8,12,16,24,31] }),
  groove({ id:"funk-groove-into-fill", name:"Funk Groove → Fill", level:"Advanced", style:"Groove + fill", meter:"2 bars · 4/4", feel:"straight", focus:"Preserve the syncopated pocket through the fill", description:"A syncopated sixteenth-note funk bar moves into a linear fill that resolves with a crash.", subdivision:16, beats:8, defaultBpm:86, tempoRange:[55,125], hats:[0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30], kicks:[0,7,10,16,23,26], snares:[4,12,20,28], toms:[17,19,21,24,25,27,29], crashes:[0,31], accents:[0,4,8,12,16,24,31] }),
  groove({ id:"shuffle-groove-into-fill", name:"Shuffle → Triplet Fill", level:"Advanced", style:"Groove + fill", meter:"2 bars · 4/4", feel:"triplet", focus:"Keep the swung subdivision consistent into the fill", description:"A blues shuffle bar followed by a triplet-based snare and tom fill with a clear resolution.", subdivision:12, beats:8, defaultBpm:82, tempoRange:[55,120], hats:[0,2,3,5,6,8,9,11], kicks:[0,6], snares:[3,9,12,15,18,21], toms:[13,14,16,17,19,20,22], crashes:[0,23], accents:[0,3,6,9,12,18,23] }),
  groove({ id:"half-time-groove-into-fill", name:"Half-Time Groove → Fill", level:"Advanced", style:"Groove + fill", meter:"2 bars · 4/4", feel:"straight", focus:"Hold the slow backbeat while counting the faster fill", description:"A spacious half-time first bar contrasts with a sixteenth-note fill in the second bar.", subdivision:16, beats:8, defaultBpm:74, tempoRange:[50,110], hats:[0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30], kicks:[0,10,16,24], snares:[8,24,26,28], toms:[21,22,23,25,27,29,30], crashes:[0,31], accents:[0,8,16,24,31] })
];

export const rudiments: Rudiment[] = [
  { id:"single-stroke", name:"Single Stroke Roll", level:"Beginner", sticking:"R L R L", coaching:"Let the stick rebound; match the height of both hands.", description:"Even alternating hands, the foundation of speed and control.", subdivision:8, beats:4, defaultBpm:70, tempoRange:[40,140], hits:[0,1,2,3,4,5,6,7].map((step)=>({step,instrument:"snare"})) },
  { id:"double-stroke", name:"Double Stroke Roll", level:"Intermediate", sticking:"R R L L", coaching:"Make the second stroke rebound, not squeeze.", description:"Two controlled strokes per hand with consistent spacing.", subdivision:16, beats:2, defaultBpm:76, tempoRange:[50,150], hits:[0,1,2,3,4,5,6,7].map((step)=>({step,instrument:"snare"})) },
  { id:"paradiddle", name:"Single Paradiddle", level:"Intermediate", sticking:"R L R R  L R L L", coaching:"Accent the first note of each four-note group.", description:"Alternating singles and doubles that unlock orchestration.", subdivision:16, beats:2, defaultBpm:80, tempoRange:[50,160], hits:[0,1,2,3,4,5,6,7].map((step)=>({step,instrument:"snare",accent:step===0||step===4})) },
  { id:"six-stroke", name:"Six Stroke Roll", level:"Advanced", sticking:"R L L R R L", coaching:"Keep the doubles low and the outside singles relaxed.", description:"A flowing six-note phrase for fills and solos.", subdivision:16, beats:3, defaultBpm:92, tempoRange:[55,170], hits:[0,1,2,3,4,5].map((step)=>({step,instrument:"snare",accent:step===0||step===5})) }
];

export const patterns: PracticePattern[] = [...grooves, ...rudiments];

export const lessons: Lesson[] = [
  {id:"meet-the-kit",order:1,level:"Beginner",title:"Meet the kit",duration:8,summary:"Learn the core voices, balanced setup, and safe listening habits.",goals:["Name five kit voices","Set a relaxed seat height","Choose hearing protection"]},
  {id:"count-the-grid",order:2,level:"Beginner",title:"Count the grid",duration:10,summary:"Read quarter and eighth notes as positions in time.",goals:["Count 1 & 2 &","Follow the playhead","Hold a steady pulse"],practicePatternId:"single-stroke"},
  {id:"first-backbeat",order:3,level:"Beginner",title:"Build your first backbeat",duration:12,summary:"Coordinate kick, snare, and hi-hat into a full groove.",goals:["Place snare on 2 and 4","Keep eighth-note hats even","Loop four bars"],practicePatternId:"first-beat"},
  {id:"first-fill",order:4,level:"Beginner",title:"A fill that lands",duration:10,summary:"Move singles around the kit and return cleanly to beat one.",goals:["Lead with either hand","Move without rushing","Crash with the kick"]},
  {id:"sixteenth-control",order:5,level:"Intermediate",title:"Sixteenth-note control",duration:14,summary:"Subdivide one beat into four equally spaced notes.",goals:["Count e & a","Keep accents intentional","Relax at higher tempos"],practicePatternId:"double-stroke"},
  {id:"paradiddle-voices",order:6,level:"Intermediate",title:"Orchestrate the paradiddle",duration:15,summary:"Turn sticking into musical movement between snare and toms.",goals:["Hear the lead-hand change","Move accents","Keep doubles soft"],practicePatternId:"paradiddle"},
  {id:"syncopated-pocket",order:7,level:"Intermediate",title:"Own the offbeat",duration:14,summary:"Add syncopated kick notes without disturbing the snare.",goals:["Anchor 2 and 4","Place offbeat kicks","Maintain dynamic balance"],practicePatternId:"syncopated-funk"},
  {id:"linear-fill",order:8,level:"Intermediate",title:"Linear fill design",duration:12,summary:"Build fills where no two limbs strike together.",goals:["Use K R L groupings","Shape dynamics","Resolve on beat one"]},
  {id:"limb-independence",order:9,level:"Advanced",title:"Layer independence",duration:18,summary:"Hold a foot ostinato while your hands phrase above it.",goals:["Internalize the feet","Add one hand at a time","Recover without stopping"]},
  {id:"five-four",order:10,level:"Advanced",title:"Make five feel natural",duration:16,summary:"Group 5/4 as 3 + 2 and create a repeatable pocket.",goals:["Count two groupings","Mark the downbeat","Phrase across the bar"],practicePatternId:"five-four-drive"},
  {id:"dynamic-arc",order:11,level:"Advanced",title:"Shape a dynamic arc",duration:14,summary:"Control ghost notes, accents, and crescendos without changing tempo.",goals:["Separate tap and accent heights","Build four-bar arcs","Keep pulse independent of volume"],practicePatternId:"six-stroke"},
  {id:"three-over-two",order:12,level:"Advanced",title:"Hear three over two",duration:18,summary:"Understand and coordinate the 3:2 polyrhythm.",goals:["Sing both layers","Play each limb alone","Combine at a slow pulse"]}
];

export function validateCurriculum() {
  const ids = [...lessons, ...patterns].map((item) => item.id);
  return {
    uniqueIds: new Set(ids).size === ids.length,
    validTempos: patterns.every((p) => p.defaultBpm >= p.tempoRange[0] && p.defaultBpm <= p.tempoRange[1]),
    validHits: patterns.every((p) => p.hits.every((hit) => hit.step >= 0 && hit.step < p.beats * (p.subdivision / 4)))
  };
}
