import { describe, expect, it } from "vitest";
import { advanceTempoRamp, allSongs, emptySongLibrary, examples, findSongs, mergeSongLibraries, migrateSongLibrary, newSong, normalizeSong, readiness, recordSongScore, reviewSection, songPartPattern, validPart } from "@/lib/song-library";

describe("song library", () => {
  it("recovers from invalid state and preserves valid songs", () => { expect(migrateSongLibrary({ version: 9 })).toEqual(emptySongLibrary()); expect(migrateSongLibrary({ version: 1, songs: [newSong("A", "B"), { title: "broken" }] }).songs).toHaveLength(1); });
  it("rejects out-of-bounds and unknown drum hits", () => { const part = examples[0].sections[0].parts[0]; expect(validPart(part)).toBe(true); expect(validPart({ ...part, hits: [{ step: 8, instrument: "kick" }] })).toBe(false); expect(validPart({ ...part, hits: [{ step: 0, instrument: "guitar" }] })).toBe(false); });
  it("searches title, artist and tags and builds a playable pattern", () => { expect(findSongs(examples, "sky")).toHaveLength(1); expect(findSongs(examples, "original")).toHaveLength(2); const p = songPartPattern(examples[0], examples[0].sections[0], examples[0].sections[0].parts[0]); expect(p.id).toBe("song:example-steady-road:verse:main"); expect(p.hits.length).toBeGreaterThan(0); });
  it("keeps favorites and merges records by id", () => { const song = newSong("New", "Drummer"); const a = { ...emptySongLibrary(), songs: [song], favorites: [song.id] }; const b = { ...emptySongLibrary(), collections: [{ id: "c", name: "Set", songIds: [song.id] }] }; const merged = mergeSongLibraries(a, b); expect(allSongs(merged)).toHaveLength(3); expect(merged.collections[0].songIds).toContain(song.id); expect(merged.favorites).toContain(song.id); });
  it("records practice by song and section", () => { const a = recordSongScore(emptySongLibrary(), "song", "verse", 80); const b = recordSongScore(a, "song", "verse", 60); expect(b.progress[0].sessions).toBe(2); expect(b.progress[0].bestScore).toBe(80); });
  it("schedules reviews and advances tempo ramps", () => { const reviewed = reviewSection(emptySongLibrary(), "s", "v", "good", new Date("2026-01-01T00:00:00Z")); expect(reviewed.reviews[0].dueAt).toBe("2026-01-03T00:00:00.000Z"); const ramp = { id: "r", songId: "s", sectionId: "v", startBpm: 70, targetBpm: 80, currentBpm: 70, stepBpm: 5, successfulPasses: 0 }; const advanced = advanceTempoRamp({ ...reviewed, tempoRamps: [ramp] }, "r", true); expect(advanced.tempoRamps[0].currentBpm).toBe(75); expect(readiness(emptySongLibrary(), examples[0]).ready).toBe(false); });
  it("requires title and artist for import", () => { expect(normalizeSong({ title: "", artist: "A", sections: [] })).toBeNull(); });
});
